### ISSUE TITLE
Mentions not working while ignoring topic

### ISSUE THREAD

**Issue by ic3fresh** [julianlam/nodebb-plugin-mentions#105]
Hi,
As I can see the mentions do not work for topic that you ignore. I think they should be "over" and give notification to person even if he has topic ignored.

Can you please check if this is correct?

**Comment by julianlam** [comment]
v2.3.0

**Comment by julianlam** [comment]
Oh, just to be clear, I didn't change the logic, I added a toggle in the Mentions plugin settings allowing you to override a topic ignores and send a mention notification regardless.

**Comment by ic3fresh** [comment]
Yeah, I can see that :) This seems to be even better fix. Thank you very much!
