### ISSUE TITLE
Code blocks are not ignored

### ISSUE THREAD

**Issue by pitaj** [julianlam/nodebb-plugin-mentions#107]
Mentions inside code blocks are not ignored by this plugin. 

See https://github.com/NodeBB/nodebb-plugin-emoji/blob/master/lib/parse.ts#L81 for a regex that could help with this.

Here's an example post: https://community.nodebb.org/post/72224

NodeBB/NodeBB#7132

julianlam/nodebb-plugin-markdown#100

**Comment by julianlam** [comment]
v2.5.1 @pitaj -- unfortunately regex changes don't work because it's not the capturing that's the problem, it's the actual hyperlinking that is at fault.

**Comment by julianlam** [comment]
v2.5.2 also fixes an issue with notifications going out if mentions are in a code block, so thanks for the heads up anyway :laughing:
