### ISSUE TITLE
Groups: Use "Title of Members" instead of "Name"

### ISSUE THREAD

**Issue by PostMidnight** [julianlam/nodebb-plugin-mentions#108]
Current status:
The mention plugin currently uses the "Name" field

Potential improvement:
Use the "Title of Members" field instead.

For foreign languages in which the character set is not a, b, c..., it is preferable to keep the group name in English (so as the JS code and database searches won't have to deal with UTF-8 strings), while the translation is kept in "title of members" input.

**Comment by julianlam** [comment]
This makes a lot of sense, will do.

**Comment by PostMidnight** [comment]
A side point: it may be preferable to assign groups with groupid (gid), a unique integer that can be queried, like you can do with uids. Its much easier to process numbers than strings...

**Comment by PostMidnight** [comment]
Finally I figured it out, we can do it ;)
Since we need to change the core a bit, with your permission I'll post the code in nodebb.
