### ISSUE TITLE
Bad matchers in Mentions.split + a solution proposed

### ISSUE THREAD

**Issue by alfazaz** [julianlam/nodebb-plugin-mentions#113]
Hello !

I found something wrong in this plugin. In Mentions.split function, there is the following matcher :
`
var matchers = [isMarkdown ? '\\[.*?\\]\\(.*?\\)' : '<a\\s[\\s\\S]*?</a>|<[^>]+>'];
`
but it doesn't work, for example, in the following case... With this content to split : 

```
<p dir="auto">@scoubidou <eq><span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>l</mi></mrow><annotation encoding="application/x-tex">l</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.69444em;vertical-align:0em;"></span><span class="mord mathdefault" style="margin-right:0.01968em;">l</span></span></span></span></eq> @alfazaz <a href=""></a></p>
```

it misses @alfazaz because the matcher get all things between `<annotation` and `</a>`.

I think the good line in Mentions.split would be (look at the \\s added) : 
`
var matchers = [isMarkdown ? '\\[.*?\\]\\(.*?\\)' : '<a\\s[\\s\\S]*?</a>|<[^>]+>'];
`

What do you think about it ? Can you fix your plugin with this (if there is no possible side effect...) ? 

Thanks !

**Comment by julianlam** [comment]
Looks good! Ideally we would have some tests written so we can easily make changes to the regex and not accidentally introduce regressions. I'll do that and make this change at the same time... :soon:

**Comment by alfazaz** [comment]
Ok ! Thanks.

**Comment by julianlam** [comment]
This is taking longer than I expected (due to time constraints and such), but I also discovered that the HTML matcher itself doesn't seem to be working properly... in that it matches all tags. Not sure at this time whether this is intentional or not...

**Comment by alfazaz** [comment]
Ah... On my site, I see no problem with HTML matcher for now (but I'm not an expert of all possible cases).

**Comment by julianlam** [comment]
v2.6.0 :smile:

**Comment by alfazaz** [comment]
Thanks :-)

**Comment by alfazaz** [comment]
Detail : I don't know why but my nodebb is still on nodebb-plugin-mentions 2.5.2 and it doesn't tell me that there is a 2.6.1 version on admin/extend/plugins#upgrade... 

Is it normal ?

**Comment by julianlam** [comment]
Could be that latest mentions requires latest development version of NodeBB. You could probably install the latest version of mentions via npm however

**Comment by alfazaz** [comment]
Ok. Thanks.
