### ISSUE TITLE
Use FULLNAME instead of USERNAME

### ISSUE THREAD

**Issue by magnusvhendin** [julianlam/nodebb-plugin-mentions#114]
I'm working for a client that wants their forum a bit more formal, and would like to use `fullname` instead of `username`. Would be awesome if this could be a setting in the admin panel. `username` could still be the identifier, but `fullname` the display name.

If I get some spare time I will have a go at implementing a solution and do a pull request, but right now other things have higher priority.

**Comment by julianlam** [comment]
While this is possible, "Full Name" is not a required profile setting, and so toggling such an option on might cause issues if the field is left blank in their profile.

**Comment by magnusvhendin** [comment]
I agree, but having it as the preferred display variable. The username could still be the identifier.

**Comment by julianlam** [comment]
v2.7.0
