### ISSUE TITLE
server shutdown since 2.7.0 on nodebb 1.12.2

### ISSUE THREAD

**Issue by alfazaz** [julianlam/nodebb-plugin-mentions#115]
Hello !

When I upgrade from nodebb-plugin-mentions 2.6.1 (which works well) to 2.7.0, my nodebb 1.12.2 server crashes when on usual pages (no problem on ACP). Here are the logs : 

> 2019-09-07T16:45:10.796Z [5678/28495] - verbose: [plugins/fireHook] action:plugins.firehook
> 2019-09-07T16:45:10.798Z [5678/28495] - error: uncaughtException: callback is not a function
> TypeError: callback is not a function
>     at /home/alfazaz/Site/Developpement/nodebb/src/user/data.js:113:4
>     at /home/alfazaz/Site/Developpement/nodebb/node_modules/async/dist/async.js:473:16
>     at next (/home/alfazaz/Site/Developpement/nodebb/node_modules/async/dist/async.js:5329:29)
>     at /home/alfazaz/Site/Developpement/nodebb/node_modules/async/dist/async.js:969:16
>     at done (/home/alfazaz/Site/Developpement/nodebb/src/plugins/hooks.js:95:5)
>     at /home/alfazaz/Site/Developpement/nodebb/node_modules/async/dist/async.js:473:16
>     at /home/alfazaz/Site/Developpement/nodebb/node_modules/async/dist/async.js:2521:9
>     at /home/alfazaz/Site/Developpement/nodebb/node_modules/async/dist/async.js:473:16
>     at replenish (/home/alfazaz/Site/Developpement/nodebb/node_modules/async/dist/async.js:1006:25)
>     at iterateeCallback (/home/alfazaz/Site/Developpement/nodebb/node_modules/async/dist/async.js:995:17) {"error":{},"stack":"TypeError: callback is not a function\n    at /home/alfazaz/Site/Developpement/nodebb/src/user/data.js:113:4\n    at /home/alfazaz/Site/Developpement/nodebb/node_modules/async/dist/async.js:473:16\n    at next (/home/alfazaz/Site/Developpement/nodebb/node_modules/async/dist/async.js:5329:29)\n    at /home/alfazaz/Site/Developpement/nodebb/node_modules/async/dist/async.js:969:16\n    at done (/home/alfazaz/Site/Developpement/nodebb/src/plugins/hooks.js:95:5)\n    at /home/alfazaz/Site/Developpement/nodebb/node_modules/async/dist/async.js:473:16\n    at /home/alfazaz/Site/Developpement/nodebb/node_modules/async/dist/async.js:2521:9\n    at /home/alfazaz/Site/Developpement/nodebb/node_modules/async/dist/async.js:473:16\n    at replenish (/home/alfazaz/Site/Developpement/nodebb/node_modules/async/dist/async.js:1006:25)\n    at iterateeCallback (/home/alfazaz/Site/Developpement/nodebb/node_modules/async/dist/async.js:995:17)","exception":true,"date":"Sat Sep 07 2019 18:45:10 GMT+0200 (heure d’été d’Europe centrale)","process":{"pid":28495,"uid":1000,"gid":100,"cwd":"/home/alfazaz/Site/Developpement/nodebb","execPath":"/usr/bin/node","version":"v10.16.3","argv":["/usr/bin/node","/home/alfazaz/Site/Developpement/nodebb/app.js"],"memoryUsage":{"rss":173420544,"heapTotal":132767744,"heapUsed":93025128,"external":37188019}},"os":{"loadavg":[2.318359375,2.20751953125,2.0693359375],"uptime":107803},"trace":[{"column":4,"file":"/home/alfazaz/Site/Developpement/nodebb/src/user/data.js","function":null,"line":113,"method":null,"native":false},{"column":16,"file":"/home/alfazaz/Site/Developpement/nodebb/node_modules/async/dist/async.js","function":null,"line":473,"method":null,"native":false},{"column":29,"file":"/home/alfazaz/Site/Developpement/nodebb/node_modules/async/dist/async.js","function":"next","line":5329,"method":null,"native":false},{"column":16,"file":"/home/alfazaz/Site/Developpement/nodebb/node_modules/async/dist/async.js","function":null,"line":969,"method":null,"native":false},{"column":5,"file":"/home/alfazaz/Site/Developpement/nodebb/src/plugins/hooks.js","function":"done","line":95,"method":null,"native":false},{"column":16,"file":"/home/alfazaz/Site/Developpement/nodebb/node_modules/async/dist/async.js","function":null,"line":473,"method":null,"native":false},{"column":9,"file":"/home/alfazaz/Site/Developpement/nodebb/node_modules/async/dist/async.js","function":null,"line":2521,"method":null,"native":false},{"column":16,"file":"/home/alfazaz/Site/Developpement/nodebb/node_modules/async/dist/async.js","function":null,"line":473,"method":null,"native":false},{"column":25,"file":"/home/alfazaz/Site/Developpement/nodebb/node_modules/async/dist/async.js","function":"replenish","line":1006,"method":null,"native":false},{"column":17,"file":"/home/alfazaz/Site/Developpement/nodebb/node_modules/async/dist/async.js","function":"iterateeCallback","line":995,"method":null,"native":false}]}
> 2019-09-07T16:45:10.798Z [5678/28495] - error: callback is not a function
> 2019-09-07T16:45:10.798Z [5678/28495] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
> 2019-09-07T16:45:10.800Z [5678/28495] - info: [app] Web server closed to connections.
> 2019-09-07T16:45:10.813Z [5678/28495] - verbose: [plugins/fireHook] filter:user.whitelistFields
> 2019-09-07T16:45:10.813Z [5678/28495] - verbose: [plugins/fireHook] action:plugins.firehook

If nodebb-plugin-mentions@2.7.0 is not compatible with nodebb 1.12.2 (but with master), it shouldn't be installable on nodebb 1.12.2.

Hope it's not a personal mistake ;-)...

**Comment by barisusakli** [comment]
Yeah I think 2.7.0 is only compatible with master so package.json needs the compat. string updated.

**Comment by alfazaz** [comment]
Ok. Thanks.

**Comment by julianlam** [comment]
My apologies, I'll deprecated 2.7.0 and republish 2.7.1 shortly.

**Comment by julianlam** [comment]
nbbpm now recommends v2.6.1 as latest got NodeBB v1.12.1

https://packages.nodebb.org/api/v1/suggest?package=nodebb-plugin-mentions&version=1.12.2

**Comment by alfazaz** [comment]
Ok... You should do the same thing with nodebb-plugin-composer-default (the last good version for nodebb 1.12.2 seems to be the 6.3.6 and it still proposes to upgrade to 6.3.11 in /admin/extend/plugins#upgrade ).

**Comment by julianlam** [comment]
Thanks for the heads-up! I do recall something similar happened to another package but couldn't remember which package it was.

**Comment by alfazaz** [comment]
;-)

**Comment by julianlam** [comment]
v6.3.9 of composer-default should work with v1.12.2. If it doesn't, please let me know what the error is. I don't see any breaking changes besides the most recent one introduced in v6.3.10

**Comment by alfazaz** [comment]
Ok. I will redo tests and open an issue if necessary on composer-default repository.

**Comment by alfazaz** [comment]
After tests, there seems to be no problem with nodebb v1.12.2 and composer-default@6.3.9 for now.

**Comment by julianlam** [comment]
Thank you -- 6.3.10/11 have been deprecated and nbbpm reflect this now.
