### ISSUE TITLE
Missing french translations

### ISSUE THREAD

**Issue by alfazaz** [julianlam/nodebb-plugin-mentions#120]
Hello !

There are missing french translations in languages/fr/notifications.json. Here is a proposition :
```
{
	"mentions": "Mentions",
	"user_mentioned_you_in": "<strong>%1</strong> vous a mentionné dans <strong>%2</strong>",
	"user_mentioned_group_in": "<strong>%1</strong> a mentionné <strong>%2</strong> dans <strong>%3</strong>",
	"notificationType_mention": "Lorsque quelqu'un vous mentionne"
}
```
If think it can be easily adjusted ;-) .

**Comment by julianlam** [comment]
v2.7.4

**Comment by alfazaz** [comment]
Thanks and... happy new year ! ;-)

**Comment by alfazaz** [comment]
@julianlam There is something wrong with npmjs synchro ?

> *** npm install nodebb-plugin-mentions@2.7.4
> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for nodebb-plugin-mentions@2.7.4.
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.

**Comment by julianlam** [comment]
Should be good now

**Comment by alfazaz** [comment]
Yes, thanks !
