### ISSUE TITLE
 Mentions do not work properly for followed topic

### ISSUE THREAD

**Issue by roghaye-m** [julianlam/nodebb-plugin-mentions#129]
I have not selected this option. 

![image](https://user-images.githubusercontent.com/37838903/99278893-dd436200-2844-11eb-9884-96673733faa5.png)

But when a user follows a topic, he does not receive a separate notification for mentions

**Comment by barisusakli** [comment]
Maybe [this](https://github.com/NodeBB/NodeBB/issues/8787) conflicts with this option

**Comment by julianlam** [comment]
Oh wow, looks like I solved the problem 2x. Once by disabling mentions for followed topics, and another time with the mergeUid. I think I will revert the newer one.

**Comment by julianlam** [comment]
Try with v2.13.5 please 

2fbde60720416bd0affbdd1b3f724ca2a695d4a7
