### ISSUE TITLE
 Rename the references to the username 

### ISSUE THREAD

**Issue by chezfo** [julianlam/nodebb-plugin-mentions#136]
When changing a username
The mentions remain ownerless
I am asking for a plugin that solves the problem
That when the username changes, along with it The mentions change to the new name

The idea can be improved
That when the previous name is mentioned, in the combination of @, the new name will be registered as a mention

https://community.nodebb.org/topic/15579/rename-the-references-to-the-username

**Comment by julianlam** [comment]
Handled in #50 

It may seem like #50 is an abandoned issue, but this has recently been top of mind, so I will look into this again, time permitting :smile: 

Thanks for reporting!
