### ISSUE TITLE
cant mention turkish usernames

### ISSUE THREAD

**Issue by barisusakli** [julianlam/nodebb-plugin-mentions#170]
Create two users 
username 1: `Muhammed lkan Coskun`
username 2: `Muhammed İlkan Coşkun`

Clicking reply on their posts adds the mention into the post body but username 2 can't be mentioned.

Did some console.log in parse method seems regex doesn't get the complete username for username 2

```
// post 1
split content [ '<p dir="auto">my first post</p>\n' ]
split content [ '<p dir="auto">@muhammed-lkan-coskun it works</p>\n' ]
matches [ '@muhammed-lkan-coskun' ] // works here

// post 2
split content [ '<p dir="auto">now with turkish characters</p>\n' ]
split content [ '<p dir="auto">@muhammed-i̇lkan-coşkun a mention</p>\n' ]
matches [ '@muhammed-i' ] // seems like doesnt match the whole thing
```

**Comment by barisusakli** [comment]
Got the fix from https://github.com/julianlam/nodebb-plugin-mentions/blob/master/static/autofill.js#L59, since selecting these usernames from the autofill dropdown was working, turns out the autofill dropdown is preserving the case so the turkish capital i wasn't converted into a weird character.

**Comment by julianlam** [comment]
:clap: for the fix, looked like a tough one to narrow down
