### ISSUE TITLE
changes didn't save

### ISSUE THREAD

**Issue by roghaye-m** [julianlam/nodebb-plugin-mentions#174]
hi, I changed some of setting in ACP (/admin/plugins/mentions)
but when I clicked on save button, it didn't work.
I use  NodeBB v1.19.3.

**Comment by barisusakli** [comment]
What version of the mentions plugin? Any errors in the browser console?

**Comment by roghaye-m** [comment]
the Latest version, 3.0.5
![image](https://user-images.githubusercontent.com/37838903/155400278-7f8559f2-b77d-4305-9fea-c90a6b195255.png)

**Comment by barisusakli** [comment]
Latest is 3.0.6, please try that.

**Comment by roghaye-m** [comment]
It didn't available on ACP panel

**Comment by barisusakli** [comment]
Yeah that's a know issue https://github.com/NodeBB/nodebb-package-manager/issues/26, try installing via cli

**Comment by julianlam** [comment]
Markdown is pinned and bundled so it isn't upgradable from ACP. I'll backport it to the release branch.
