### ISSUE TITLE
erased usernames "[[global:former_user]]" are suggested by the plugin

### ISSUE THREAD

**Issue by AliCihan** [julianlam/nodebb-plugin-mentions#176]
composer is suggesting non-existent users since they have posts under the topic. 

<img width="367" alt="Screen Shot 2022-03-01 at 12 25 17 PM" src="https://user-images.githubusercontent.com/52054408/156218467-671349fc-5782-411a-9077-374938355aa3.png">

**Comment by barisusakli** [comment]
nodebb-plugin-mentions@3.0.7, let me know if it works on 3.0.7
