### ISSUE TITLE
Group's mention in posts doesn't work if group name not in English

### ISSUE THREAD

**Issue by MegaGM** [julianlam/nodebb-plugin-mentions#46]
![](http://i.imgur.com/Fva4wW2.png)

**Comment by MegaGM** [comment]
https://github.com/julianlam/nodebb-plugin-mentions/pull/47

**Comment by julianlam** [comment]
:smile:

**Comment by MegaGM** [comment]
![](http://smayly.ru/gallery/ava/Kanade/58.jpg)
