### ISSUE TITLE
a@b.com matches as mention

### ISSUE THREAD

**Issue by barisusakli** [julianlam/nodebb-plugin-mentions#48]
matches as a mention with the current regex

`regex = XRegExp('(@[\\p{L}\\d\\-_.]+)', 'g'),`

**Comment by barisusakli** [comment]
https://github.com/julianlam/nodebb-plugin-markdown/issues/51

if there is a user named `derp` then the following renders incorrectly

`<email@derp.com>` 

results in 

`@derp" rel="nofollow">email@exodo`

**Comment by julianlam** [comment]
Bug opened March 12 :laughing:

**Comment by julianlam** [comment]
v1.0.3
