### ISSUE TITLE
use case for group mentions?

### ISSUE THREAD

**Issue by ahthamrin** [julianlam/nodebb-plugin-mentions#54]
Hi

I'd like to know the use case for group mentions as my understanding are:
1. it does not generate notifications
2. it exposes hidden groups

If my understanding are correct, then I'd like to see the group mentions removed.

Thanks

**Comment by barisusakli** [comment]
1. Mentioning a group should send a notification to all the members.
2. Hidden groups shouldn't show up in the mentions dropdown.

**Comment by ahthamrin** [comment]
I tried both use cases and I found that
1. no notification for group members when I mentioned the group
2. the mentions dropdown showed hidden groups.

Would you check?
Thanks
