### ISSUE TITLE
mentions replaced inside links

### ISSUE THREAD

**Issue by BenLubar** [julianlam/nodebb-plugin-mentions#71]
Steps to reproduce:

1. make a topic with a mention before the end of its title
2. reply to the topic, quoting the first post
3. the link to the topic is cut off by the mention's nested link

**Comment by julianlam** [comment]
:clap:

**Comment by pitaj** [comment]
Is this fixed or not?

**Comment by BenLubar** [comment]
This was fixed by #74.
