### ISSUE TITLE
takes to localhost

### ISSUE THREAD

**Issue by lestus** [julianlam/nodebb-plugin-mentions#73]
I 'love' your one-line comment of 'change your config.json'. 'Very Helpful', maybe to someone who already knows how, why and where to configure said file, in which case your 'helpful' post is already moot, because it's only helping people who already know what the solution is.. wtf.
how about a proper breakdown step by step, where the hell I find this file, what I need to edit (that i can guess), if there are any commands afterwards needing to be ran for recompiling or restarting the server or anything along those lines. I'm just saying, I'm clearly salty at finding incomplete information when I'm searching for a solution to a problem.

**Comment by julianlam** [comment]
The file is in your NodeBB root. Restart NodeBB after you edit it.

Closing this as it is not an issue.

**Comment by julianlam** [comment]
If you need additional help, you're advised to post in the community support forum as your issue will be seen by more people who can help.

https://community.nodebb.org
