### ISSUE TITLE
Feature request: separate group mentions from user mentions

### ISSUE THREAD

**Issue by yamikuronue** [julianlam/nodebb-plugin-mentions#76]
I'm a moderator on a NodeBB instance, and I typically get a number of mention notifications in a day. I'd like to be able to distinguish in the notification when someone typed @mods and when they typed @yamikuronue so I know if they wanted me specifically or any moderator (as the latter is usually answered by the time I get there).

**Comment by pauljherring** [comment]
Not gone upstream yet?

**Comment by BenLubar** [comment]
This *is* the upstream ticket.

**Comment by pauljherring** [comment]
Ah - I clearly haven't had enough ethanol...

**Comment by abarker-TDWTF** [comment]
Unfortunately, I suspect this is a duplicate of [issue #72](https://github.com/julianlam/nodebb-plugin-mentions/issues/72).

**Comment by tehspaceg** [comment]
I'd like to take this a step further and be able to disable notifications for groups on a per user basis. Lets say UserMcGee is in a group that we use solely to gain access to another category, that person may not care about notifications. GroupMcAdminPants might want to continue getting notifications.

**Comment by BenLubar** [comment]
@tehspaceg maybe it would be best to make receiving mentions for a group an opt-in thing per-group? I can see how mentioning `@administrators` or `@People-Interested-In-NodeBB-Development` would be useful whereas mentioning `@some-group-with-a-thousand-members-that-grants-access-to-a-category` would be a bad thing.

**Comment by tehspaceg** [comment]
@BenLubar that would be the perfect functionality. Opt-in to receive notifications from certain group mentions.
