### ISSUE TITLE
ability to disable group mentions

### ISSUE THREAD

**Issue by barisusakli** [julianlam/nodebb-plugin-mentions#85]

**Comment by DomLennonZA** [comment]
I am currently working on this. To achieve this I am creating a management page for the ACP. I am having issues getting my template to be copied over when building NodeBB. I have added `"templates": "./public/templates"` to the `plugin.json`, and have added a file called `mentions,tpl` which can be found in `template/admin/plugins/`. When running ./nodebb build, or just running the app in general, it doesnt seem to copy to the public templates folder. If I copy it there manually it works fine. Am I doing something wrong? @julianlam @barisusakli

**Comment by pichalite** [comment]
@DomLennonZA Is your checked in to github so we can check and point out any mistakes?

**Comment by DomLennonZA** [comment]
@pichalite False alarm. I had a bit of the Monday's and it seems I just had the folder marked as read-only :P

**Comment by julianlam** [comment]
Done now 😄
