### ISSUE TITLE
send him/her a email when @him/@her

### ISSUE THREAD

**Issue by YanhaoMo** [julianlam/nodebb-plugin-mentions#88]
When I @ someone in NodeBB, I want him/her will receive a email about the mention on his/her offline.
But I haven't found how to config this, Or this has not been implemented yet?
Can you add this feature please?

**Comment by michaelpfaff** [comment]
I don't think think this feature currently exists but agree it should be a high priority.

**Comment by julianlam** [comment]
Dupe of #75
