### ISSUE TITLE
User slug not generating link to user profile on a post reply.

### ISSUE THREAD

**Issue by jarey** [julianlam/nodebb-plugin-mentions#89]
Just saw the issue on the community.nodebb.org site:

Can be reproduced/seen on this post: https://community.nodebb.org/topic/10098/loading-nodebb-in-my-site-through-iframe

I think the problem should be the space or ' character present in the username but don't really know.

Thank you!
PS: Related to #44

**Comment by julianlam** [comment]
Thanks, yes it is the space and `'`... specifically, when you hit "reply", it should properly slugify the name, but it doesn't quite match the server-side one...
