### ISSUE TITLE
Font size for mentions is off

### ISSUE THREAD

**Issue by psychobunny** [julianlam/nodebb-plugin-mentions#92]
```
.plugin-mentions-a {
    color: #31708f;
    font-size: .9em;
    white-space: nowrap;
}
```

IMO drop font size, and let the theme handle it. Right now in persona, mentions are a touch smaller than the rest of the text, which is weird.

Might be an artifact from back in the day when mentions had this border and padding shenanigans going on haha

**Comment by julianlam** [comment]
👍  iirc font size was set because it used to show a little badge in place of the username (plus online/offline status).
