### ISSUE TITLE
Default mention notification setting

### ISSUE THREAD

**Issue by SaitDev** [julianlam/nodebb-plugin-mentions#99]
Usually, the expected behave when we mention someone is wanna get their attention. But by default mention notification setting is "Do nothing", each user will need to change this themself on their setting page. Most new user will never know this 😞 

Can we have an option on admin plugin page to set default notification for mention? or at least by default the setting is "Only notification" for all user

**Comment by pitaj** [comment]
You can configure the defaults for all of those settings in the ACP > Settings > User > **Default Notification Settings**

**Comment by barisusakli** [comment]
Looks like mentions isn't added in that default settings page, I will fix it
